qa:
  yml:
jobs:
  - name: integration
    max_in_flight: 1
    plan:
      - get: dataworks-aws-tarball-ingester
        trigger: true
        passed:
          - qa
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'integration'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'integration'
