jobs:
  - name: dataworks-aws-tarball-ingester-pr
    plan:
      - get: dataworks-tarball-ingester-release
        trigger: false
      - get: dataworks-aws-tarball-ingester-pr
        trigger: true
        version: every
      - put: dataworks-aws-tarball-ingester-pr
        params:
          path: dataworks-aws-tarball-ingester-pr
          status: pending
      - get: dw-al2-hardened-ami
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-aws-tarball-ingester: dataworks-aws-tarball-ingester-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-aws-tarball-ingester: dataworks-aws-tarball-ingester-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: dataworks-aws-tarball-ingester-pr
          params:
            path: dataworks-aws-tarball-ingester-pr
            status: failure
        on_success:
          put: dataworks-aws-tarball-ingester-pr
          params:
            path: dataworks-aws-tarball-ingester-pr
            status: success
