jobs:
  - name: production
    max_in_flight: 1
    plan:
      - get: dataworks-aws-tarball-ingester
        trigger: true
        passed:
          - preprod
      - get: dataworks-tarball-ingester-release
        trigger: false
        passed:
          - preprod
      - get: dw-al2-hardened-ami
        trigger: false
        passed:
          - preprod
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'production'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'production'
