meta:
  plan:

    terraform-common-config:
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.terraform_repository))
            tag: ((dataworks.terraform_version))
        params:
          TF_INPUT: false
          TF_CLI_ARGS_apply: -lock-timeout=300s
          TF_CLI_ARGS_plan: -lock-timeout=300s
          TF_VAR_costcode: ((dataworks.costcode))

    terraform-bootstrap:
      task: terraform-bootstrap
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dwpdigital/jinja-yaml-aws
            version: 0.0.19
            tag: 0.0.19
        run:
          path: sh
          args:
            - -exc
            - |
              python bootstrap_terraform.py
              cp terraform.tf ../terraform-bootstrap
          dir: dataworks-aws-tarball-ingester
        inputs:
          - name: dataworks-aws-tarball-ingester
        outputs:
          - name: terraform-bootstrap
      params:
        AWS_REGION: eu-west-2

    terraform-apply:
      task: terraform-apply
      .: (( inject meta.plan.terraform-common-config ))
      config:
        run:
          path: sh
          args:
            - -exc
            - |
              export TF_VAR_al2_hardened_ami_id=$(cat ../dw-al2-hardened-ami/id)
              export TF_VAR_tarball_ingester_release=$(cat ../dataworks-tarball-ingester-release/version)
              cp ../terraform-bootstrap/terraform.tf .
              terraform workspace show
              terraform init
              terraform plan -out terraform.plan
              terraform apply -auto-approve terraform.plan
          dir: dataworks-aws-tarball-ingester
        inputs:
          - name: dataworks-aws-tarball-ingester
          - name: terraform-bootstrap
          - name: dw-al2-hardened-ami
          - name: dataworks-tarball-ingester-release


    terraform-plan:
      task: terraform-plan
      .: (( inject meta.plan.terraform-common-config ))
      config:
        run:
          path: sh
          args:
            - -exc
            - |
              export TF_VAR_al2_hardened_ami_id=$(cat ../dw-al2-hardened-ami/id)
              export TF_VAR_tarball_ingester_release=$(cat ../dataworks-tarball-ingester-release/version)
              cp ../terraform-bootstrap/terraform.tf .
              terraform workspace show
              terraform init
              terraform plan $DETAILED_EXITCODE
          dir: dataworks-aws-tarball-ingester
        inputs:
          - name: dataworks-aws-tarball-ingester
          - name: terraform-bootstrap
          - name: dw-al2-hardened-ami
          - name: dataworks-tarball-ingester-release
      params:
        DETAILED_EXITCODE: -detailed-exitcode

    terraform-output-management-infra:
      task: terraform-output-management-infra
      .: (( inject meta.plan.terraform-common-config ))
      config:
        params:
          TF_WORKSPACE: management
        run:
          path: sh
          dir: aws-management-infrastructure
          args:
            - -exc
            - |
              terraform init
              terraform workspace show
              terraform output artefact_bucket | grep "\"id\" = " | awk '{print $3}' | sed 's/"//g' > ../bucket-name/bucket-name
        inputs:
          - name: aws-management-infrastructure
        outputs:
          - name: bucket-name

    terraform-output:
      task: terraform-output
      .: (( inject meta.plan.terraform-common-config ))
      config:
        run:
          path: sh
          dir: dataworks-aws-tarball-ingester
          args:
            - -exc
            - |
              cp ../terraform-bootstrap/terraform.tf .
              terraform init
              terraform workspace show
              terraform output ingester_asg | grep "\"name\" = " | awk '{print $3}' | sed 's/"//g' > ../ingester-asg/name
        inputs:
          - name: dataworks-aws-tarball-ingester
          - name: terraform-bootstrap
        outputs:
          - name: ingester-asg

    scale-up:
      task: scale-up
      .: (( inject meta.plan.terraform-common-config ))
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.docker_awscli_repository))
            version: ((dataworks.docker_awscli_version))
            tag: ((dataworks.docker_awscli_version))
        inputs:
          - name: ingester-asg
        params:
          AWS_REGION: ((dataworks.aws_region))
          AWS_DEFAULT_REGION: ((dataworks.aws_region))
        run:
          path: sh
          args:
            - -exc
            - |
              source /assume-role
              set +x
              export ASG_NAME=$(cat ingester-asg/name)
              echo "Scaling up ${ASG_NAME} to 1..."
              ASG_SCALING=$(aws autoscaling set-desired-capacity --auto-scaling-group-name ${ASG_NAME} --desired-capacity 1)
              if $ASG_SCALING; then
                echo "Scaling successful."
              else
                echo "Scaling failed."
              fi

    scale-down:
      task: scale-down
      .: (( inject meta.plan.terraform-common-config ))
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.docker_awscli_repository))
            version: ((dataworks.docker_awscli_version))
            tag: ((dataworks.docker_awscli_version))
        inputs:
          - name: ingester-asg
        params:
          AWS_REGION: ((dataworks.aws_region))
          AWS_DEFAULT_REGION: ((dataworks.aws_region))
        run:
          path: sh
          args:
            - -exc
            - |
              source /assume-role
              set +x
              export ASG_NAME=$(cat ingester-asg/name)
              echo "Scaling down ${ASG_NAME} to 0..."
              ASG_SCALING=$(aws autoscaling set-desired-capacity --auto-scaling-group-name ${ASG_NAME} --desired-capacity 0)
              if $ASG_SCALING; then
                echo "Scaling successful."
              else
                echo "Scaling failed."
              fi